### PR TITLE
Make sure socket and auth microservices don't fail - adding npm install before running them

### PR DESCRIPTION
**Pull request by ErezAmihud**
Solve https://github.com/breuerfelix/instapy-gui/issues/139

### CODE REVIEW

**Comment by breuerfelix** [comment]
@ErezAmihud  thanks for the PR, is the npm install really nessecary ? or does it work if you just do sh -c "npm run dev" ?

**Comment by ErezAmihud** [comment]
I have tried to run it multiple times, deleting and recreating the images, and now somehow the way it was before this pull request works. Closing due to no Idea what is going on.

**Comment by breuerfelix** [comment]
@ErezAmihud glad to hear that! and thanks for the investigation :) at least now i switched from travis to github actions to get PRs working again!

**Comment by ErezAmihud** [comment]
So I sadly needed to change my workstation, and the problem happened again. I found out that the reason it worked is probably that node_modules package was in the `service/auth` or `service/socket`.

The error that was is:
```
npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! instapy-auth@1.0.0 start: `node index.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the instapy-auth@1.0.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

Also I saw the github actions, nicely done :)

**Comment by breuerfelix** [comment]
@ErezAmihud ahhh now i know why and when this happens! i mount the whole folder to the docker container in order to have your latest scripts inside the container for development but so is your node_modules folder mounted. that means when you have node_modules installed locally, it will work but if you only develop inside the container (which is the reason why i made the dev setup), this won't work unless you installed the modules locally

so i will merge these changes since now you are able to fully work in containers without even having node installed on your system :)

**Pull request merged**
